export const EMPIRE_AGENTS = [
  {
    id: "orchestrator",
    name: "Empire Orchestrator",
    team: "command",
    mission: "Decide which agents are needed for a content run and assemble their outputs into one execution plan. Prefer slightly longer complete shorts with setup, escalation, payoff, and a final beat.",
    inputs: ["niche", "platform", "goal", "references", "analytics", "budget"],
    outputs: ["agentBrief", "taskAssignments", "goNoGo"],
    canSpawn: ["reference-analyst", "niche-scout", "hook-writer", "higgsfield-director", "quality-gate", "posting-operator"],
  },
  {
    id: "reference-analyst",
    name: "Reference Analyst",
    team: "creative-intelligence",
    mission: "Study reference videos/accounts and extract reusable patterns without copying protected footage or exact creator wording. For horror, identify tension build, jump-scare timing, and aftermath beats.",
    inputs: ["referenceUrls", "referenceNotes", "niche"],
    outputs: ["winningPatterns", "pacingNotes", "visualLanguage", "captionStyle", "doNotCopy"],
    canSpawn: ["hook-writer", "higgsfield-director"],
  },
  {
    id: "trend-radar",
    name: "Trend Radar",
    team: "growth",
    mission: "Watch current platform trends, formats, sounds, topics, and audience behavior for timely content opportunities.",
    inputs: ["platform", "niche", "searchResults", "trendNotes"],
    outputs: ["trendBrief", "urgentOpportunities", "trendRisk"],
    canSpawn: ["niche-scout", "competitor-tracker", "content-strategist"],
  },
  {
    id: "competitor-tracker",
    name: "Competitor Tracker",
    team: "creative-intelligence",
    mission: "Track target pages and competitors, then identify repeatable winners without copying footage or wording.",
    inputs: ["accountUrls", "recentVideos", "publicMetrics", "niche"],
    outputs: ["competitorBrief", "winningFormats", "postingPatterns", "contentGaps"],
    canSpawn: ["reference-analyst", "experiment-manager"],
  },
  {
    id: "niche-scout",
    name: "Niche Scout",
    team: "growth",
    mission: "Find and rank niches that deserve testing, scaling, pausing, or killing.",
    inputs: ["analytics", "scheduledPosts", "trendNotes"],
    outputs: ["launch", "scale", "test", "kill"],
    canSpawn: ["reference-analyst", "content-strategist"],
  },
  {
    id: "audience-psychologist",
    name: "Audience Psychologist",
    team: "strategy",
    mission: "Define why the target viewer keeps watching, shares, comments, or follows.",
    inputs: ["niche", "audience", "comments", "analytics"],
    outputs: ["viewerMotivations", "curiosityDrivers", "emotionalTriggers", "avoidList"],
    canSpawn: ["hook-writer", "content-strategist"],
  },
  {
    id: "content-strategist",
    name: "Content Strategist",
    team: "creative",
    mission: "Turn niche signals into original video concepts with a clear audience, promise, escalation, payoff, and enough story to support a slightly longer short.",
    inputs: ["niche", "patterns", "audience", "analytics"],
    outputs: ["videoConcepts", "seriesIdeas", "captionAngles"],
    canSpawn: ["hook-writer", "voice-director"],
  },
  {
    id: "series-architect",
    name: "Series Architect",
    team: "creative",
    mission: "Turn one-off ideas into repeatable series formats that can scale across channels.",
    inputs: ["niche", "winningPatterns", "analytics", "audienceMotivations"],
    outputs: ["seriesFormats", "episodeRules", "repeatableTemplates"],
    canSpawn: ["content-strategist", "prompt-librarian"],
  },
  {
    id: "hook-writer",
    name: "Hook Writer",
    team: "creative",
    mission: "Create first-second hooks, retention beats, captions, and reveals for short-form videos. For horror, script a slow dread build into one clear platform-safe jump scare and a final unsettling after-beat.",
    inputs: ["concept", "niche", "referencePatterns"],
    outputs: ["hook", "scriptBeats", "caption", "hashtags"],
    canSpawn: ["quality-gate"],
  },
  {
    id: "script-doctor",
    name: "Script Doctor",
    team: "creative",
    mission: "Tighten scripts so every sentence earns retention while preserving a complete setup, escalation, payoff, and final beat. Horror scripts must include a clear jump-scare moment without gore.",
    inputs: ["hook", "script", "niche", "audience"],
    outputs: ["revisedScript", "cutNotes", "retentionBeats"],
    canSpawn: ["retention-editor", "quality-gate"],
  },
  {
    id: "higgsfield-director",
    name: "Higgsfield Director",
    team: "video",
    mission: "Convert approved scripts into Higgsfield-ready cinematic prompts and generation settings. Target longer, complete shorts; for horror, include tension build, a sharp jump-scare reveal, and a short aftermath beat.",
    inputs: ["script", "hook", "niche", "style", "referencePatterns"],
    outputs: ["higgsfieldPrompt", "modelSettings", "negativePrompt", "qualityChecklist"],
    canSpawn: ["quality-gate", "budget-watcher"],
  },
  {
    id: "prompt-librarian",
    name: "Prompt Librarian",
    team: "video",
    mission: "Store, version, and reuse the best Higgsfield prompts and settings by niche and style, including horror jump-scare timing and longer-video pacing templates.",
    inputs: ["higgsfieldPrompt", "videoResult", "qualityScore", "analytics"],
    outputs: ["promptTemplate", "promptVersion", "reuseRecommendation"],
    canSpawn: ["higgsfield-director", "experiment-manager"],
  },
  {
    id: "first-frame-agent",
    name: "First Frame Agent",
    team: "video",
    mission: "Optimize the first visual frame and first second so viewers stop scrolling.",
    inputs: ["videoConcept", "hook", "style", "referencePatterns"],
    outputs: ["firstFramePrompt", "openingShot", "scrollStopperScore"],
    canSpawn: ["higgsfield-director", "quality-gate"],
  },
  {
    id: "retention-editor",
    name: "Retention Editor",
    team: "video",
    mission: "Find slow starts, dead spots, weak reveals, and pacing problems before publishing. For horror, require a suspense ramp, jump-scare payoff, and short aftermath without dragging.",
    inputs: ["script", "video", "captions", "referencePacing"],
    outputs: ["retentionScore", "fixNotes", "regenerationInstructions"],
    canSpawn: ["script-doctor", "higgsfield-director"],
  },
  {
    id: "voice-director",
    name: "Voice Director",
    team: "video",
    mission: "Pick voice, tone, pacing, and caption rhythm for each niche.",
    inputs: ["niche", "audience", "style", "script"],
    outputs: ["voiceProfile", "captionPacing", "soundNotes"],
    canSpawn: ["quality-gate"],
  },
  {
    id: "caption-seo-agent",
    name: "Caption SEO Agent",
    team: "distribution",
    mission: "Optimize captions, hashtags, keywords, titles, and platform text for discovery and clicks.",
    inputs: ["caption", "niche", "platform", "trendTags"],
    outputs: ["caption", "hashtags", "platformTitle", "searchKeywords"],
    canSpawn: ["quality-gate"],
  },
  {
    id: "platform-adapter",
    name: "Platform Adapter",
    team: "distribution",
    mission: "Adjust one approved concept for TikTok, Instagram Reels, YouTube Shorts, and posts.",
    inputs: ["video", "caption", "platform", "channelRules"],
    outputs: ["platformPackage", "postingNotes", "formatWarnings"],
    canSpawn: ["caption-seo-agent", "posting-operator"],
  },
  {
    id: "quality-gate",
    name: "Quality Gate",
    team: "safety-quality",
    mission: "Block weak, unsafe, off-brand, static, too-short, or low-retention videos before posting. Horror may use jump scares, but must stay platform-safe and non-graphic.",
    inputs: ["post", "video", "niche", "audience", "policyResult"],
    outputs: ["pass", "failReasons", "regenerationNotes"],
    canSpawn: ["hook-writer", "higgsfield-director"],
  },
  {
    id: "compliance-safety-agent",
    name: "Compliance Safety Agent",
    team: "safety-quality",
    mission: "Apply stricter checks for kids, horror, finance, claims, platform rules, and brand safety. Horror jump scares are allowed only when non-graphic, non-harmful, and platform-safe.",
    inputs: ["post", "video", "audience", "niche", "platform"],
    outputs: ["safetyStatus", "blockedReasons", "requiredEdits"],
    canSpawn: ["quality-gate", "script-doctor"],
  },
  {
    id: "posting-operator",
    name: "Posting Operator",
    team: "distribution",
    mission: "Schedule approved videos through Postiz and record posting memory.",
    inputs: ["approvedVideo", "caption", "channel", "scheduleTime"],
    outputs: ["postizResult", "scheduledPostMemory"],
    canSpawn: ["social-watcher"],
  },
  {
    id: "schedule-optimizer",
    name: "Schedule Optimizer",
    team: "distribution",
    mission: "Pick posting times and cadence by niche, platform, channel history, and testing plan.",
    inputs: ["channel", "platform", "analytics", "plannedPosts"],
    outputs: ["scheduleTimes", "cadence", "postingPriority"],
    canSpawn: ["posting-operator", "experiment-manager"],
  },
  {
    id: "analytics-agent",
    name: "Analytics Agent",
    team: "growth",
    mission: "Read performance data and turn winners/losers into the next content instructions.",
    inputs: ["recentPosts", "views", "likes", "comments", "shares", "watchTime"],
    outputs: ["winnerPatterns", "loserPatterns", "nextTests"],
    canSpawn: ["niche-scout", "content-strategist"],
  },
  {
    id: "experiment-manager",
    name: "Experiment Manager",
    team: "growth",
    mission: "Run structured tests for hooks, formats, prompts, captions, posting times, niches, video length, and horror jump-scare timing.",
    inputs: ["hypotheses", "analytics", "budget", "channels"],
    outputs: ["testPlan", "variants", "successCriteria", "winnerDecision"],
    canSpawn: ["hook-writer", "higgsfield-director", "caption-seo-agent"],
  },
  {
    id: "asset-librarian",
    name: "Asset Librarian",
    team: "ops",
    mission: "Store and organize generated videos, scripts, prompts, winners, losers, and reusable assets.",
    inputs: ["video", "script", "prompt", "analytics", "postizResult"],
    outputs: ["assetRecord", "retrievalTags", "reuseNotes"],
    canSpawn: ["prompt-librarian", "analytics-agent"],
  },
  {
    id: "revenue-agent",
    name: "Revenue Agent",
    team: "monetization",
    mission: "Identify monetization angles such as affiliates, lead magnets, products, sponsors, and offers.",
    inputs: ["niche", "audience", "analytics", "channelTrust"],
    outputs: ["revenueIdeas", "offerFit", "ctaRules", "riskWarnings"],
    canSpawn: ["content-strategist", "compliance-safety-agent"],
  },
  {
    id: "funnel-agent",
    name: "Funnel Agent",
    team: "monetization",
    mission: "Connect viral content to email lists, landing pages, offers, and conversion paths.",
    inputs: ["revenueIdea", "platform", "bioLink", "audience"],
    outputs: ["funnelPlan", "landingPageBrief", "conversionCTA"],
    canSpawn: ["revenue-agent", "caption-seo-agent"],
  },
  {
    id: "community-agent",
    name: "Community Agent",
    team: "growth",
    mission: "Analyze comments, questions, objections, and viewer language to create better future videos.",
    inputs: ["comments", "dms", "postPerformance"],
    outputs: ["viewerQuestions", "replyIdeas", "nextVideoIdeas"],
    canSpawn: ["content-strategist", "analytics-agent"],
  },
  {
    id: "budget-watcher",
    name: "Budget Watcher",
    team: "ops",
    mission: "Protect Higgsfield credits and daily spend limits.",
    inputs: ["dailySpend", "budget", "plannedRenders"],
    outputs: ["budgetStatus", "allowedRenders", "pauseRecommendation"],
    canSpawn: ["orchestrator"],
  },
  {
    id: "tool-scout",
    name: "Tool Scout",
    team: "ops",
    mission: "Find useful plugins, skills, libraries, and workflow upgrades, then recommend safe installs.",
    inputs: ["currentStack", "taskNeeds", "knownLimitations"],
    outputs: ["toolRecommendations", "installRisk", "expectedBenefit"],
    canSpawn: ["orchestrator", "compliance-safety-agent"],
  },
  {
    id: "social-watcher",
    name: "Social Watcher",
    team: "ops",
    mission: "Monitor Postiz/social account connection health and publishing failures.",
    inputs: ["postizChannels", "recentPosts", "integrationStatus"],
    outputs: ["connectionHealth", "reauthNeeded", "postingIssues"],
    canSpawn: ["posting-operator"],
  },
  {
    id: "railway-watcher",
    name: "Railway Watcher",
    team: "ops",
    mission: "Monitor worker uptime, deployment status, and production incidents.",
    inputs: ["healthEndpoint", "opsReport", "deploymentState"],
    outputs: ["serviceHealth", "incidentReport"],
    canSpawn: ["orchestrator"],
  },
];

export function listAgents() {
  return EMPIRE_AGENTS.map((agent) => ({ ...agent }));
}

export function getAgent(id) {
  return EMPIRE_AGENTS.find((agent) => agent.id === id) || null;
}

export function agentsByTeam() {
  return EMPIRE_AGENTS.reduce((acc, agent) => {
    acc[agent.team] = [...(acc[agent.team] || []), agent];
    return acc;
  }, {});
}
