export const AGENT_SQUADS = [
  {
    id: "horror-video-production",
    name: "Horror Video Production Squad",
    task: "Create one premium horror short from idea to approved Higgsfield video.",
    lead: "orchestrator",
    agents: [
      "trend-radar",
      "competitor-tracker",
      "reference-analyst",
      "audience-psychologist",
      "content-strategist",
      "hook-writer",
      "script-doctor",
      "first-frame-agent",
      "higgsfield-director",
      "voice-director",
      "retention-editor",
      "compliance-safety-agent",
      "quality-gate",
    ],
    success: "A vertical Higgsfield video that passes safety, retention, and quality gates.",
  },
  {
    id: "kids-video-production",
    name: "Kids Video Production Squad",
    task: "Create one safe, cheerful kids short.",
    lead: "orchestrator",
    agents: [
      "trend-radar",
      "reference-analyst",
      "audience-psychologist",
      "content-strategist",
      "hook-writer",
      "script-doctor",
      "higgsfield-director",
      "voice-director",
      "caption-seo-agent",
      "compliance-safety-agent",
      "quality-gate",
    ],
    success: "A parent-safe vertical video with cheerful voice, bright visuals, and no unsafe content.",
  },
  {
    id: "brainrot-video-production",
    name: "Brainrot Video Production Squad",
    task: "Create one fast viral meme/Gen Z short.",
    lead: "orchestrator",
    agents: [
      "trend-radar",
      "competitor-tracker",
      "reference-analyst",
      "content-strategist",
      "hook-writer",
      "script-doctor",
      "higgsfield-director",
      "voice-director",
      "retention-editor",
      "caption-seo-agent",
      "compliance-safety-agent",
      "quality-gate",
    ],
    success: "A fast, original, safe teen-facing video with constant motion and strong captions.",
  },
  {
    id: "niche-discovery",
    name: "Niche Discovery Squad",
    task: "Find, score, and prioritize new niches.",
    lead: "niche-scout",
    agents: [
      "trend-radar",
      "competitor-tracker",
      "analytics-agent",
      "audience-psychologist",
      "revenue-agent",
      "experiment-manager",
    ],
    success: "A ranked list of launch, test, scale, pause, and kill recommendations.",
  },
  {
    id: "reference-research",
    name: "Reference Research Squad",
    task: "Analyze target creators/pages and extract repeatable patterns.",
    lead: "reference-analyst",
    agents: [
      "competitor-tracker",
      "reference-analyst",
      "audience-psychologist",
      "retention-editor",
      "caption-seo-agent",
      "prompt-librarian",
    ],
    success: "A reference brief with hooks, pacing, visual language, caption rules, and do-not-copy warnings.",
  },
  {
    id: "publishing",
    name: "Publishing Squad",
    task: "Turn an approved video into scheduled platform posts.",
    lead: "posting-operator",
    agents: [
      "platform-adapter",
      "caption-seo-agent",
      "schedule-optimizer",
      "posting-operator",
      "social-watcher",
      "asset-librarian",
    ],
    success: "Approved media is scheduled through Postiz and recorded in memory.",
  },
  {
    id: "analytics-feedback",
    name: "Analytics Feedback Squad",
    task: "Learn from performance and decide what to make next.",
    lead: "analytics-agent",
    agents: [
      "analytics-agent",
      "community-agent",
      "niche-scout",
      "experiment-manager",
      "content-strategist",
      "prompt-librarian",
      "revenue-agent",
    ],
    success: "Clear next actions based on winners, losers, comments, and monetization signals.",
  },
  {
    id: "ops-safety",
    name: "Ops Safety Squad",
    task: "Keep the system live, safe, connected, and within budget.",
    lead: "orchestrator",
    agents: [
      "budget-watcher",
      "railway-watcher",
      "social-watcher",
      "compliance-safety-agent",
      "quality-gate",
      "tool-scout",
    ],
    success: "No unsafe posts, no uncontrolled spend, no broken publishing pipeline.",
  },
  {
    id: "monetization",
    name: "Monetization Squad",
    task: "Turn audience growth into responsible revenue.",
    lead: "revenue-agent",
    agents: [
      "revenue-agent",
      "funnel-agent",
      "audience-psychologist",
      "content-strategist",
      "caption-seo-agent",
      "compliance-safety-agent",
      "analytics-agent",
    ],
    success: "A monetization plan that fits the niche without hurting trust or violating policy.",
  },
];

export function listSquads() {
  return AGENT_SQUADS.map((squad) => ({ ...squad, agents: [...squad.agents] }));
}

export function getSquad(id) {
  return AGENT_SQUADS.find((squad) => squad.id === id) || null;
}

export function squadsForAgent(agentId) {
  return AGENT_SQUADS.filter((squad) => squad.lead === agentId || squad.agents.includes(agentId));
}
